# Generated by Django 4.2.28 on 2026-03-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_databasehistory_facts_institution_reportingyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
