# Generated by Django 4.2.28 on 2026-03-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_upload_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
